config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    resources :products do
      collection do
        get 'search'
      end
    end
  end

end

app/models/spree/product.rb
# PRODUCTS
# Products represent an entity for sale in a store.
# Products can have variations, called variants
# Products properties include description, permalink, availability,
#   shipping category, etc. that do not change by variant.
#
# MASTER VARIANT
# Every product has one master variant, which stores master price and sku, size and weight, etc.
# The master variant does not have option values associated with it.
# Price, SKU, size, weight, etc. are all delegated to the master variant.
# Contains on_hand inventory levels only when there are no variants for the product.
#
# VARIANTS
# All variants can access the product properties directly (via reverse delegation).
# Inventory units are tied to Variant.
# The master variant can have inventory units, but not option values.
# All other variants have option values and may have inventory units.
# Sum of on_hand each variant's inventory level determine "on_hand" level for the product.
#
require 'elasticsearch/model'

module Spree
  class Product < Spree::Base
    
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    


    #def search_data
      #{
        #machine_models: machine_models
      #}
    #end


    extend FriendlyId
    friendly_id :slug_candidates, use: :history

    acts_as_paranoid

    has_many :product_option_types, dependent: :destroy, inverse_of: :product
    has_many :option_types, through: :product_option_types
    has_many :product_properties, dependent: :destroy, inverse_of: :product
    has_many :properties, through: :product_properties

    has_many :classifications, dependent: :delete_all, inverse_of: :product
    has_many :taxons, through: :classifications, before_remove: :remove_taxon
    has_and_belongs_to_many :promotion_rules, join_table: :spree_products_promotion_rules

    belongs_to :tax_category, class_name: 'Spree::TaxCategory'
    belongs_to :shipping_category, class_name: 'Spree::ShippingCategory', inverse_of: :products

    has_one :master,
      -> { where is_master: true },
      inverse_of: :product,
      class_name: 'Spree::Variant'

    has_many :variants,
      -> { where(is_master: false).order("#{::Spree::Variant.quoted_table_name}.position ASC") },
      inverse_of: :product,
      class_name: 'Spree::Variant'

    has_many :variants_including_master,
      -> { order("#{::Spree::Variant.quoted_table_name}.position ASC") },
      inverse_of: :product,
      class_name: 'Spree::Variant',
      dependent: :destroy

    has_many :prices, -> { order('spree_variants.position, spree_variants.id, currency') }, through: :variants

    has_many :stock_items, through: :variants_including_master

    has_many :line_items, through: :variants_including_master
    has_many :orders, through: :line_items

    delegate_belongs_to :master, :sku, :price, :currency, :display_amount, :display_price, :weight, :height, :width, :depth, :is_master, :has_default_price?, :cost_currency, :price_in, :amount_in

    delegate_belongs_to :master, :cost_price

    delegate :images, to: :master, prefix: true
    alias_method :images, :master_images

    has_many :variant_images, -> { order(:position) }, source: :images, through: :variants_including_master

    after_create :set_master_variant_defaults
    after_create :add_associations_from_prototype
    after_create :build_variants_from_option_values_hash, if: :option_values_hash

    after_destroy :punch_slug
    after_restore :update_slug_history

    after_initialize :ensure_master

    after_save :save_master
    after_save :run_touch_callbacks, if: :anything_changed?
    after_save :reset_nested_changes
    after_touch :touch_taxons

    before_validation :normalize_slug, on: :update
    before_validation :validate_master

    validates :meta_keywords, length: { maximum: 255 }
    validates :meta_title, length: { maximum: 255 }
    validates :name, presence: true
    validates :price, presence: true, if: proc { Spree::Config[:require_master_price] }
    validates :shipping_category_id, presence: true
    validates :slug, length: { minimum: 3 }, allow_blank: true, uniqueness: true

    attr_accessor :option_values_hash

    accepts_nested_attributes_for :product_properties, allow_destroy: true, reject_if: lambda { |pp| pp[:property_name].blank? }

    alias :options :product_option_types

    self.whitelisted_ransackable_associations = %w[stores variants_including_master master variants]
    self.whitelisted_ransackable_attributes = %w[description name slug]

    # the master variant is not a member of the variants array
    def has_variants?
      variants.any?
    end

    def tax_category
      if self[:tax_category_id].nil?
        TaxCategory.where(is_default: true).first
      else
        TaxCategory.find(self[:tax_category_id])
      end
    end

    # Adding properties and option types on creation based on a chosen prototype
    attr_reader :prototype_id
    def prototype_id=(value)
      @prototype_id = value.to_i
    end

    # Ensures option_types and product_option_types exist for keys in option_values_hash
    def ensure_option_types_exist_for_values_hash
      return if option_values_hash.nil?
      option_values_hash.keys.map(&:to_i).each do |id|
        self.option_type_ids << id unless option_type_ids.include?(id)
        product_option_types.create(option_type_id: id) unless product_option_types.pluck(:option_type_id).include?(id)
      end
    end

    # for adding products which are closely related to existing ones
    # define "duplicate_extra" for site-specific actions, eg for additional fields
    def duplicate
      duplicator = ProductDuplicator.new(self)
      duplicator.duplicate
    end

    # use deleted? rather than checking the attribute directly. this
    # allows extensions to override deleted? if they want to provide
    # their own definition.
    def deleted?
      !!deleted_at
    end

    # determine if product is available.
    # deleted products and products with nil or future available_on date
    # are not available
    def available?
      !(available_on.nil? || available_on.future?) && !deleted?
    end

    # split variants list into hash which shows mapping of opt value onto matching variants
    # eg categorise_variants_from_option(color) => {"red" -> [...], "blue" -> [...]}
    def categorise_variants_from_option(opt_type)
      return {} unless option_types.include?(opt_type)
      variants.active.group_by { |v| v.option_values.detect { |o| o.option_type == opt_type} }
    end

    def self.like_any(fields, values)
      where fields.map { |field|
        values.map { |value|
          arel_table[field].matches("%#{value}%")
        }.inject(:or)
      }.inject(:or)
    end

    # Suitable for displaying only variants that has at least one option value.
    # There may be scenarios where an option type is removed and along with it
    # all option values. At that point all variants associated with only those
    # values should not be displayed to frontend users. Otherwise it breaks the
    # idea of having variants
    def variants_and_option_values(current_currency = nil)
      variants.includes(:option_values).active(current_currency).select do |variant|
        variant.option_values.any?
      end
    end

    def empty_option_values?
      options.empty? || options.any? do |opt|
        opt.option_type.option_values.empty?
      end
    end

    def property(property_name)
      return nil unless prop = properties.find_by(name: property_name)
      product_properties.find_by(property: prop).try(:value)
    end

    def set_property(property_name, property_value)
      ActiveRecord::Base.transaction do
        # Works around spree_i18n #301
        property = if Property.exists?(name: property_name)
          Property.where(name: property_name).first
        else
          Property.create(name: property_name, presentation: property_name)
        end
        product_property = ProductProperty.where(product: self, property: property).first_or_initialize
        product_property.value = property_value
        product_property.save!
      end
    end

    def possible_promotions
      promotion_ids = promotion_rules.map(&:promotion_id).uniq
      Spree::Promotion.advertised.where(id: promotion_ids).reject(&:expired?)
    end

    def total_on_hand
      if any_variants_not_track_inventory?
        Float::INFINITY
      else
        stock_items.sum(:count_on_hand)
      end
    end

    # Master variant may be deleted (i.e. when the product is deleted)
    # which would make AR's default finder return nil.
    # This is a stopgap for that little problem.
    def master
      super || variants_including_master.with_deleted.where(is_master: true).first
    end

    private

    def add_associations_from_prototype
      if prototype_id && prototype = Spree::Prototype.find_by(id: prototype_id)
        prototype.properties.each do |property|
          product_properties.create(property: property)
        end
        self.option_types = prototype.option_types
        self.taxons = prototype.taxons
      end
    end

    def any_variants_not_track_inventory?
      if variants_including_master.loaded?
        variants_including_master.any? { |v| !v.should_track_inventory? }
      else
        !Spree::Config.track_inventory_levels || variants_including_master.where(track_inventory: false).any?
      end
    end

    # Builds variants from a hash of option types & values
    def build_variants_from_option_values_hash
      ensure_option_types_exist_for_values_hash
      values = option_values_hash.values
      values = values.inject(values.shift) { |memo, value| memo.product(value).map(&:flatten) }

      values.each do |ids|
        variant = variants.create(
          option_value_ids: ids,
          price: master.price
        )
      end
      save
    end

    def ensure_master
      return unless new_record?
      self.master ||= build_master
    end

    def normalize_slug

app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < Spree::StoreController
    before_action :load_product, only: :show
    before_action :load_taxon, only: :index

    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      if params[:search].present?
        @query = params[:search].presence || "*"
        @products = Spree::Product.__elasticsearch__.search(params[:search]).records
      else
        @products = Spree::Product.all
      end
    end


    def show
	  @imageProds = "http://ts.liveofficedata.co.uk/" + @product.image_url
      @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
      @product_properties = @product.product_properties.includes(:property)
      @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
      redirect_if_legacy_path
    end

    private

      def accurate_title
        if @product
          @product.meta_title.blank? ? @product.name : @product.meta_title
        else
          super
        end
      end

      def load_product
        if try_spree_current_user.try(:has_spree_role?, "admin")
          @products = Product.with_deleted
        else
          @products = Product.active(current_currency)
        end
        @product = @products.friendly.find(params[:id])
      end

      def load_taxon
        @taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon].present?
      end

      def redirect_if_legacy_path
        # If an old id or a numeric id was used to find the record,
        # we should do a 301 redirect that uses the current friendly id.
        if params[:id] != @product.friendly_id
          params.merge!(id: @product.friendly_id)
          return redirect_to url_for(params), status: :moved_permanently
        end
      end
  end
end

app/views/spree/admin/products/_form.html.erb
<% if current_page?('/admin/products/customeraddress/edit') %>
	<style>
		#product_name_field, #product_slug_field, #product_sale_field, #product_featured_field, #product_latest_field, #product_description_field, #product_taxons_field, #product_featured_field, #product_option_types_field, #product_meta_title_field, #product_meta_keywords_field, #product_meta_description_field {display: none;}
		
		#admin_new_product, .main-right-sidebar, #product_price_field, #product_cost_price_field, #product_cost_currency_field, #product_available_on_field, #product_sku_field, #product_ts_code_field, #product_promotionable_field, #shipping_specs, #product_shipping_categories_field, #product_tax_category_field {display: none;}
	</style>
<% end %>

<div data-hook="admin_product_form_fields">

  <div class="row">

    <div class="col-md-8" data-hook="admin_product_form_left">
      <div data-hook="admin_product_form_name">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', class: 'required')) %>
          <%= f.text_field :name, class: 'form-control title' %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_slug">
        <%= f.field_container :slug, class: ['form-group'] do %>
          <%= f.label :slug, raw(Spree.t(:slug) + content_tag(:span, ' *', class: "required")) %>
          <%= f.text_field :slug, class: 'form-control title' %>
          <%= f.error_message_on :slug %>
        <% end %>
      </div>
      
      <%= f.field_container :sale do %>
      <%= f.check_box :sale, :class => 'fullwidth title' %>
      <%= f.label :sale, raw(Spree.t(:sale) + content_tag(:span, ' *',  :class => "required")) %>
      <%= f.error_message_on :sale %>
    <% end %>

    <%= f.field_container :featured do %>
      <%= f.check_box :featured, :class => 'fullwidth title' %>
      <%= f.label :featured, raw(Spree.t(:featured) + content_tag(:span, ' *',  :class => "required")) %>
      <%= f.error_message_on :featured %>
    <% end %>

    <%= f.field_container :latest do %>
    <%= f.check_box :latest, :class => 'fullwidth title' %>
      <%= f.label :latest, raw(Spree.t(:latest) + content_tag(:span, ' *',  :class => "required")) %>
      <%= f.error_message_on :latest %>
    <% end %>
    
    <br><br>
    
    <% if current_page?('/admin/products/customeraddress/edit') %>
    
    <h3 style="background: #5799d8;color:white;">Edit/Add Your contact details for front page</h3>
    
    <%= f.field_container :address do %>
      <%= f.text_area :address, :class => 'fullwidth title' %>
      <%= f.label :address, raw(Spree.t(:address)) %>
      <%= f.error_message_on :address %>
    <% end %>
    
    <%= f.field_container :phone do %>
      <%= f.text_field :phone, :class => 'fullwidth title' %>
      <%= f.label :phone, raw(Spree.t(:phone)) %>
      <%= f.error_message_on :phone %>
    <% end %>
    
    <%= f.field_container :email do %>
      <%= f.text_field :email, :class => 'fullwidth title' %>
      <%= f.label :email, raw(Spree.t(:email)) %>
      <%= f.error_message_on :email %>
    <% end %>
    
    <%= f.field_container :mailer do %>
      <%= f.text_field :mailer, :class => 'fullwidth title' %>
      <%= f.label :mailer, raw(Spree.t(:mailer)) %>
      <%= f.error_message_on :mailer %>
    <% end %>
    
    <%= f.field_container :facebook do %>
      <%= f.text_field :facebook, :class => 'fullwidth title' %>
      <%= f.label :facebook, raw(Spree.t(:facebook)) %><span style="float:right;margin-left:30px;background:#5799d8;color:white;">Must be in format http://www.facebook.com/username</span>
      <%= f.error_message_on :facebook %>
    <% end %>
    
    <%= f.field_container :twitter do %>
      <%= f.text_field :twitter, :class => 'fullwidth title' %>
      <%= f.label :twitter, raw(Spree.t(:twitter)) %><span style="float:right;margin-left:30px;background:#5799d8;color:white;">Must be in format http://www.twitter.com/username</span>
      <%= f.error_message_on :twitter %>
    <% end %>
    
    <%= f.field_container :linkedin do %>
      <%= f.text_field :linkedin, :class => 'fullwidth title' %>
      <%= f.label :linkedin, raw(Spree.t(:linkedin)) %><span style="float:right;margin-left:30px;background:#5799d8;color:white;">Must be in format http://www.linkedin.com/username</span>
      <%= f.error_message_on :linkedin %>
    <% end %>


    <%= f.field_container :vow_account_code do %>
      <%= f.text_field :vow_account_code, :class => 'fullwidth title' %>
      <%= f.label :vow_account_code, raw(Spree.t(:vow_account_code)) %>
      <%= f.error_message_on :vow_account_code %>
    <% end %>

    <%= f.field_container :spicers_account_code do %>
      <%= f.text_field :spicers_account_code, :class => 'fullwidth title' %>
      <%= f.label :spicers_account_code, raw(Spree.t(:spicers_account_code)) %>
      <%= f.error_message_on :spicers_account_code %>
    <% end %>

    
	<% end %>
    
    <br><br>

      <div data-hook="admin_product_form_description">
        <%= f.field_container :description, class: ['form-group'] do %>
          <%= f.label :description, Spree.t(:description) %>
          <%= f.text_area :description, { rows: "#{unless @product.has_variants? then '20' else '13' end}", class: 'form-control' } %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4" data-hook="admin_product_form_right">
      <div data-hook="admin_product_form_price">
        <%= f.field_container :price, class: ['form-group'] do %>
          <%= f.label :price, raw(Spree.t(:master_price) + content_tag(:span, ' *', class: "required")) %>
          <%= f.text_field :price, value: number_to_currency(@product.price, unit: ''), class: 'form-control', disabled: (cannot? :update, Spree::Price) %>
          <%= f.error_message_on :price %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_cost_price" class="alpha two columns">
        <%= f.field_container :cost_price, class: ['form-group'] do %>
          <%= f.label :cost_price, Spree.t(:cost_price) %>
          <%= f.text_field :cost_price, value: number_to_currency(@product.cost_price, unit: ''), class: 'form-control' %>
          <%= f.error_message_on :cost_price %>
        <% end %>
      </div>
      <div data-hook="admin_product_form_cost_currency" class="omega two columns">
        <%= f.field_container :cost_currency, class: ['form-group'] do %>
          <%= f.label :cost_currency, Spree.t(:cost_currency) %>
          <%= f.text_field :cost_currency, class: 'form-control' %>
          <%= f.error_message_on :cost_currency %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_available_on">
        <%= f.field_container :available_on, class: ['form-group'] do %>
          <%= f.label :available_on, Spree.t(:available_on) %>
          <%= f.error_message_on :available_on %>
          <%= f.text_field :available_on, value: datepicker_field_value(@product.available_on), class: 'datepicker form-control' %>
        <% end %>
      </div>

      <% if @product.has_variants? %>
        <div data-hook="admin_product_form_multiple_variants" class="well">
          <%= f.label :skus, Spree.t(:sku).pluralize %>
          <div class="info marginb">
            <%= Spree.t(:info_product_has_multiple_skus, count: @product.variants.count) %>
            <ul class="text_list">
              <% @product.variants.first(5).each do |variant| %>
                <li><%= variant.sku %></li>
              <% end %>
            </ul>
            <% if @product.variants.count > 5 %>
              <em>
                <%= Spree.t(:info_number_of_skus_not_shown, count: @product.variants.count - 5) %>
              </em>
            <% end %>
          </div>
          <div class="info-actions">
            <% if can?(:admin, Spree::Variant) %>
              <%= link_to_with_icon 'variants', Spree.t(:manage_variants), spree.admin_product_variants_url(@product), class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div data-hook="admin_product_form_sku">
          <%= f.field_container :sku, class: ['form-group'] do %>
            <%= f.label :sku, Spree.t(:sku) %>
            <%= f.text_field :sku, size: 16, class: 'form-control' %>
          <% end %>
        </div>
        
        <%= f.field_container :ts_code do %>
	      <%= f.label :ts_code, raw(Spree.t(:ts_code)) %><br>
	      <%= f.text_field :ts_code, :class => 'fullwidth title' %>
	      <%= f.error_message_on :ts_code %>
		 <% end %><br>

        <div data-hook="admin_product_form_promotionable">
          <%= f.field_container :promotionable, class: ['form-group'] do %>
              <%= f.label :promotionable %>
              <%= f.error_message_on :promotionable %>
              <%= f.check_box :promotionable, class: 'form-control' %>
          <% end %>
        </div>

        <div id="shipping_specs" class="row">
          <div class="col-md-6">
            <div id="shipping_specs_weight_field" data-hook="admin_product_form_weight" class="form-group">
              <%= f.label :weight, Spree.t(:weight) %>
              <%= f.text_field :weight, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_height_field" data-hook="admin_product_form_height" class="form-group">
              <%= f.label :height, Spree.t(:height) %>
              <%= f.text_field :height, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_width_field" data-hook="admin_product_form_width" class="form-group">
              <%= f.label :width, Spree.t(:width) %>
              <%= f.text_field :width, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_depth_field" data-hook="admin_product_form_depth" class="form-group">
              <%= f.label :depth, Spree.t(:depth) %>
              <%= f.text_field :depth, size: 4, class: 'form-control' %>
            </div>
          </div>
        </div>
      <% end %>

      <div data-hook="admin_product_form_shipping_categories">
        <%= f.field_container :shipping_categories, class: ['form-group'] do %>
          <%= f.label :shipping_category_id, Spree.t(:shipping_categories) %>
          <%= f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', disabled: (cannot? :edit, Spree::ShippingCategory) }) %>
          <%= f.error_message_on :shipping_category %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_tax_category">
        <%= f.field_container :tax_category, class: ['form-group'] do %>
          <%= f.label :tax_category_id, Spree.t(:tax_category) %>
          <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', disabled: (cannot? :edit, Spree::TaxCategory) }) %>
          <%= f.error_message_on :tax_category %>
        <% end %>
      </div>
    </div>

  </div>

  <div data-hook="admin_product_form_taxons">
    <%= f.field_container :taxons, class: ['form-group'] do %>
      <%= f.label :taxon_ids, Spree.t(:taxons) %>

      <% if can? :modify, Spree::Classification %>
        <%= f.hidden_field :taxon_ids, value: @product.taxon_ids.join(',') %>
      <% elsif @product.taxons.any? %>
        <ul class="text_list">
          <% @product.taxons.each do |taxon| %>
            <li><%= taxon.name %></li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :taxons) %></div>
      <% end %>

    <% end %>
  </div>

  <div data-hook="admin_product_form_option_types">
    <%= f.field_container :option_types, class: ['form-group'] do %>
      <%= f.label :option_type_ids, Spree.t(:option_types) %>

      <% if can? :modify, Spree::OptionType %>
        <%= f.hidden_field :option_type_ids, value: @product.option_type_ids.join(',') %>
      <% elsif @product.option_types.any? %>
        <ul class="text_list">
          <% @product.option_types.each do |type| %>
            <li><%= type.presentation %> (<%= type.name %>)</li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :option_types) %></div>
      <% end %>

    <% end %>
  </div>


  <div data-hook="admin_product_form_meta">
    <div data-hook="admin_product_form_meta_title">
      <%= f.field_container :meta_title, class: ['form-group'] do %>
        <%= f.label :meta_title, Spree.t(:meta_title) %>
        <%= f.text_field :meta_title, class: 'form-control' %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_meta_keywords">
      <%= f.field_container :meta_keywords, class: ['form-group'] do %>
        <%= f.label :meta_keywords, Spree.t(:meta_keywords) %>
        <%= f.text_field :meta_keywords, class: 'form-control' %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_meta_description">
      <%= f.field_container :meta_description, class: ['form-group'] do %>
        <%= f.label :meta_description, Spree.t(:meta_description) %>
        <%= f.text_field :meta_description, class: 'form-control' %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_additional_fields"></div>

  </div>
</div>